Exercice 1 :

In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns

In [2]:
#0. Importation dataFrame 
diamonds = pd.read_csv('diamonds.csv')

In [3]:
#1. Afficher la description des colonnes de ce fichier
print(diamonds.info())

print(diamonds.describe)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB
None
<bound method NDFrame.describe of        carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]>

In [4]:
#2. Afficher les 50 premi√®res lignes du fichier
print(diamonds.head(50))

    carat        cut color clarity  depth  table  price     x     y     z
0    0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2    0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3    0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4    0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5    0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6    0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7    0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8    0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9    0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
10   0.30       Good     J     SI1   64.0   55.0    339  4.25  4.28  2.73
11   0.23      Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46
12   0.22    Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
13   0.31      Ideal     J     SI2   62.2   54.0    344  4.35  4.37  2.71
14   0.20    Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
15   0.32    Premium     E      I1   60.9   58.0    345  4.38  4.42  2.68
16   0.30      Ideal     I     SI2   62.0   54.0    348  4.31  4.34  2.68
17   0.30       Good     J     SI1   63.4   54.0    351  4.23  4.29  2.70
18   0.30       Good     J     SI1   63.8   56.0    351  4.23  4.26  2.71
19   0.30  Very Good     J     SI1   62.7   59.0    351  4.21  4.27  2.66
20   0.30       Good     I     SI2   63.3   56.0    351  4.26  4.30  2.71
21   0.23  Very Good     E     VS2   63.8   55.0    352  3.85  3.92  2.48
22   0.23  Very Good     H     VS1   61.0   57.0    353  3.94  3.96  2.41
23   0.31  Very Good     J     SI1   59.4   62.0    353  4.39  4.43  2.62
24   0.31  Very Good     J     SI1   58.1   62.0    353  4.44  4.47  2.59
25   0.23  Very Good     G    VVS2   60.4   58.0    354  3.97  4.01  2.41
26   0.24    Premium     I     VS1   62.5   57.0    355  3.97  3.94  2.47
27   0.30  Very Good     J     VS2   62.2   57.0    357  4.28  4.30  2.67
28   0.23  Very Good     D     VS2   60.5   61.0    357  3.96  3.97  2.40
29   0.23  Very Good     F     VS1   60.9   57.0    357  3.96  3.99  2.42
30   0.23  Very Good     F     VS1   60.0   57.0    402  4.00  4.03  2.41
31   0.23  Very Good     F     VS1   59.8   57.0    402  4.04  4.06  2.42
32   0.23  Very Good     E     VS1   60.7   59.0    402  3.97  4.01  2.42
33   0.23  Very Good     E     VS1   59.5   58.0    402  4.01  4.06  2.40
34   0.23  Very Good     D     VS1   61.9   58.0    402  3.92  3.96  2.44
35   0.23       Good     F     VS1   58.2   59.0    402  4.06  4.08  2.37
36   0.23       Good     E     VS1   64.1   59.0    402  3.83  3.85  2.46
37   0.31       Good     H     SI1   64.0   54.0    402  4.29  4.31  2.75
38   0.26  Very Good     D     VS2   60.8   59.0    403  4.13  4.16  2.52
39   0.33      Ideal     I     SI2   61.8   55.0    403  4.49  4.51  2.78
40   0.33      Ideal     I     SI2   61.2   56.0    403  4.49  4.50  2.75
41   0.33      Ideal     J     SI1   61.1   56.0    403  4.49  4.55  2.76
42   0.26       Good     D     VS2   65.2   56.0    403  3.99  4.02  2.61
43   0.26       Good     D     VS1   58.4   63.0    403  4.19  4.24  2.46
44   0.32       Good     H     SI2   63.1   56.0    403  4.34  4.37  2.75
45   0.29    Premium     F     SI1   62.4   58.0    403  4.24  4.26  2.65
46   0.32  Very Good     H     SI2   61.8   55.0    403  4.35  4.42  2.71
47   0.32       Good     H     SI2   63.8   56.0    403  4.36  4.38  2.79
48   0.25  Very Good     E     VS2   63.3   60.0    404  4.00  4.03  2.54
49   0.29  Very Good     H     SI2   60.7   60.0    404  4.33  4.37  2.64

In [5]:
#3. Afficher les donn√©es de la s√©rie ‚Äòcarat ‚Äò tri√©e par ordre croissant
diamonds.sort_values(by=['carat'], ascending=[True])

       carat      cut color clarity  depth  table  price      x      y     z
31593   0.20  Premium     E     VS2   61.1   59.0    367   3.81   3.78  2.32
31597   0.20    Ideal     D     VS2   61.5   57.0    367   3.81   3.77  2.33
31596   0.20  Premium     F     VS2   62.6   59.0    367   3.73   3.71  2.33
31595   0.20    Ideal     E     VS2   59.7   55.0    367   3.86   3.84  2.30
31594   0.20  Premium     E     VS2   59.7   62.0    367   3.84   3.80  2.28
...      ...      ...   ...     ...    ...    ...    ...    ...    ...   ...
25999   4.01  Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24
25998   4.01  Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
27130   4.13     Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
27630   4.50     Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27415   5.01     Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98

[53940 rows x 10 columns]

In [6]:
#4. N‚Äôafficher que les colonnes ‚Äòcarat‚Äô, ‚Äòcut‚Äô , ‚Äòcolor‚Äô et ‚Äòprice‚Äô
diamonds[['carat', 'cut','color','price']]

       carat        cut color  price
0       0.23      Ideal     E    326
1       0.21    Premium     E    326
2       0.23       Good     E    327
3       0.29    Premium     I    334
4       0.31       Good     J    335
...      ...        ...   ...    ...
53935   0.72      Ideal     D   2757
53936   0.72       Good     D   2757
53937   0.70  Very Good     D   2757
53938   0.86    Premium     H   2757
53939   0.75      Ideal     D   2757

[53940 rows x 4 columns]

In [7]:
#5. N‚Äôafficher que les diamants avec length>4, width>4 and depth>4
FiltredList = diamonds[(diamonds['x'] > 4) & (diamonds['y'] > 4) & (diamonds['z'] > 4)]
print(FiltredList)

       carat        cut color clarity  depth  table  price     x     y     z
97      0.96       Fair     F     SI2   66.3   62.0   2759  6.27  5.95  4.07
172     1.17  Very Good     J      I1   60.2   61.0   2774  6.83  6.90  4.13
204     0.98       Fair     H     SI2   67.9   60.0   2777  6.05  5.97  4.08
241     1.01       Fair     E      I1   64.5   58.0   2788  6.29  6.21  4.03
247     1.05  Very Good     J     SI2   63.2   56.0   2789  6.49  6.45  4.09
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53692   1.00       Good     F      I1   64.2   59.0   2717  6.26  6.30  4.03
53698   1.05       Fair     H     SI2   64.8   55.0   2717  6.39  6.32  4.12
53863   1.00       Fair     I     SI2   66.8   56.0   2743  6.22  6.12  4.13
53879   1.04       Fair     G     SI2   65.2   57.0   2745  6.25  6.23  4.07
53897   1.02       Good     H      I1   64.3   63.0   2751  6.28  6.23  4.02

[15020 rows x 10 columns]

In [8]:
#6.	Lister les diamants du type ‚ÄòFair‚Äô, ‚ÄòGood‚Äô ou ‚ÄòPremuim‚Äô 
print(diamonds[diamonds['cut'].isin(['Fair', 'Good', 'Premium'])])

       carat      cut color clarity  depth  table  price     x     y     z
1       0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
8       0.22     Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53936   0.72     Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[20307 rows x 10 columns]

In [9]:

#7.	Calculer le nombre de diamants,  le minimum et maximum du prix pour chaque ‚Äòcut‚Äô 
print(diamonds.groupby('cut')['price'].agg(['count', 'min', 'max']))

           count  min    max
cut
Fair        1610  337  18574
Good        4906  327  18788
Ideal      21551  326  18806
Premium    13791  326  18823
Very Good  12082  336  18818

In [10]:
#8.	Supprimer les lignes ne contenant pas de valeur dans les  colonnes ‚Äòcarat‚Äô et  ‚Äòcut‚Äô  
diamonds.dropna(subset=['carat', 'cut'])

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [11]:
#9.	Lister le nombre des valeurs manquantes dans chaque s√©rie 
diamonds.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [12]:
#10.     Donner les diff√©rents types de carat possibles et le nombre de diamants pour chaque.
diamonds['carat'].value_counts()

carat
0.30    2604
0.31    2249
1.01    2242
0.70    1981
0.32    1840
        ...
3.02       1
3.65       1
3.50       1
3.22       1
3.11       1
Name: count, Length: 273, dtype: int64

In [13]:
#11.	Donner le nombre de couleurs pour chaque coupe ‚Äòcut‚Äô
print(diamonds.groupby('cut')['color'].count())

print(diamonds.groupby('cut')['color'].value_counts())

cut
Fair          1610
Good          4906
Ideal        21551
Premium      13791
Very Good    12082
Name: color, dtype: int64
cut        color
Fair       G         314
           F         312
           H         303
           E         224
           I         175
           D         163
           J         119
Good       E         933
           F         909
           G         871
           H         702
           D         662
           I         522
           J         307
Ideal      G        4884
           E        3903
           F        3826
           H        3115
           D        2834
           I        2093
           J         896
Premium    G        2924
           H        2360
           E        2337
           F        2331
           D        1603
           I        1428
           J         808
Very Good  E        2400
           G        2299
           F        2164
           H        1824
           D        1513
           I        1204
           J         678
Name: count, dtype: int64

In [14]:
#12.	Lister l'ensemble de mod√®les de diamants possibles
ListModel = pd.crosstab(index=[diamonds['carat'], diamonds['cut'], diamonds['color']],columns=diamonds['clarity'])
print(ListModel)

clarity              I1  IF  SI1  SI2  VS1  VS2  VVS1  VVS2
carat cut     color
0.20  Ideal   D       0   0    0    0    0    1     0     0
              E       0   0    0    0    0    2     0     0
      Premium D       0   0    0    0    0    2     0     0
              E       0   0    0    1    0    4     0     0
              F       0   0    0    0    0    1     0     0
...                  ..  ..  ...  ...  ...  ...   ...   ...
4.01  Premium I       1   0    0    0    0    0     0     0
              J       1   0    0    0    0    0     0     0
4.13  Fair    H       1   0    0    0    0    0     0     0
4.50  Fair    J       1   0    0    0    0    0     0     0
5.01  Fair    J       1   0    0    0    0    0     0     0

[4803 rows x 8 columns]

Exercice 2 : Fusion de listes tri√©es

In [15]:
def fusion_liste(liste1, liste2):
    if not liste1:
        return liste2
    if not liste2:
        return liste1

    if liste1[-1] > liste2[-1]:
        return fusion_liste(liste1[:-1], liste2) + [liste1[-1]]
    else:
        return fusion_liste(liste1, liste2[:-1]) + [liste2[-1]]

In [18]:
liste1 = [3, 1, 4, 7, 9, 10, 11]
liste2 = [2, 5, 6, 1,6, 13]

liste1.sort()
liste2.sort()

Fusion_listes = fusion_liste(liste1, liste2)
print(Fusion_listes)

[1, 1, 2, 3, 4, 5, 6, 6, 7, 9, 10, 11, 13]